using System;
namespace OpenMeteo.Weather.ResponseModel
{
    public class Hourly
    {
        public DateTimeOffset[]? Time { get; set; }
        public float?[]? Temperature_2m { get; set; }
        public int?[]? Relativehumidity_2m { get; set; }
        public float?[]? Dewpoint_2m { get; set; }
        public float?[]? Apparent_temperature { get; set; }
        public float?[]? Precipitation { get; set; }
        public float?[]? Rain { get; set; }
        public float?[]? Showers { get; set; }
        public float?[]? Snowfall { get; set; }
        public float?[]? Snow_depth { get; set; }
        public float?[]? Snowfall_height { get; set; }
        public float?[]? Freezing_level_height { get; set; }
        public int?[]? Weathercode { get; set; }
        public float?[]? Pressure_msl { get; set; }
        public float?[]? Surface_pressure { get; set; }
        public int?[]? Cloudcover { get; set; }
        public int?[]? Cloudcover_low { get; set; }
        public int?[]? Cloudcover_mid { get; set; }
        public int?[]? Cloudcover_high { get; set; }
        public float?[]? Visibility { get; set; }
        public float?[]? Evapotranspiration { get; set; }
        public float?[]? Et0_fao_evapotranspiration { get; set; }
        public float?[]? Vapor_pressure_deficit { get; set; }
        public float?[]? Cape { get; set; }
        public float?[]? Windspeed_10m { get; set; }
        public float?[]? Windspeed_80m { get; set; }
        public float?[]? Windspeed_120m { get; set; }
        public float?[]? Windspeed_180m { get; set; }
        public int?[]? Winddirection_10m { get; set; }
        public int?[]? Winddirection_80m { get; set; }
        public int?[]? Winddirection_120m { get; set; }
        public int?[]? Winddirection_180m { get; set; }
        public float?[]? Windgusts_10m { get; set; }
        public float?[]? Temperature_80m { get; set; }
        public float?[]? Temperature_120m { get; set; }
        public float?[]? Temperature_180m { get; set; }
        public float?[]? Soil_temperature_0cm { get; set; }
        public float?[]? Soil_temperature_6cm { get; set; }
        public float?[]? Soil_temperature_18cm { get; set; }
        public float?[]? Soil_temperature_54cm { get; set; }
        public float?[]? Soil_moisture_0_1cm { get; set; }
        public float?[]? Soil_moisture_1_3cm { get; set; }
        public float?[]? Soil_moisture_3_9cm { get; set; }
        public float?[]? Soil_moisture_9_27cm { get; set; }
        public float?[]? Soil_moisture_27_81cm { get; set; }
        public float?[]? Shortwave_radiation { get; set; }
        public float?[]? Direct_radiation { get; set; }
        public float?[]? Diffuse_radiation { get; set; }
        public float?[]? Direct_normal_irradiance { get; set; }
        public float?[]? Terrestrial_radiation { get; set; }
        public float?[]? Shortwave_radiation_instant { get; set; }
        public float?[]? Direct_radiation_instant { get; set; }
        public float?[]? Diffuse_radiation_instant { get; set; }
        public float?[]? Direct_normal_irradiance_instant { get; set; }
        public float?[]? Terrestrial_radiation_instant { get; set; }
        public float?[]? Temperature_1000hPa { get; set; }
        public float?[]? Temperature_975hPa { get; set; }
        public float?[]? Temperature_950hPa { get; set; }
        public float?[]? Temperature_925hPa { get; set; }
        public float?[]? Temperature_900hPa { get; set; }
        public float?[]? Temperature_875hPa { get; set; }
        public float?[]? Temperature_850hPa { get; set; }
        public float?[]? Temperature_825hPa { get; set; }
        public float?[]? Temperature_800hPa { get; set; }
        public float?[]? Temperature_775hPa { get; set; }
        public float?[]? Temperature_750hPa { get; set; }
        public float?[]? Temperature_725hPa { get; set; }
        public float?[]? Temperature_700hPa { get; set; }
        public float?[]? Temperature_675hPa { get; set; }
        public float?[]? Temperature_650hPa { get; set; }
        public float?[]? Temperature_625hPa { get; set; }
        public float?[]? Temperature_600hPa { get; set; }
        public float?[]? Temperature_575hPa { get; set; }
        public float?[]? Temperature_550hPa { get; set; }
        public float?[]? Temperature_525hPa { get; set; }
        public float?[]? Temperature_500hPa { get; set; }
        public float?[]? Temperature_400hPa { get; set; }
        public float?[]? Temperature_300hPa { get; set; }
        public float?[]? Temperature_250hPa { get; set; }
        public float?[]? Temperature_200hPa { get; set; }
        public float?[]? Temperature_150hPa { get; set; }
        public float?[]? Temperature_100hPa { get; set; }
        public float?[]? Temperature_70hPa { get; set; }
        public float?[]? Temperature_50hPa { get; set; }
        public float?[]? Temperature_30hPa { get; set; }
        public float?[]? Dewpoint_1000hPa { get; set; }
        public float?[]? Dewpoint_975hPa { get; set; }
        public float?[]? Dewpoint_950hPa { get; set; }
        public float?[]? Dewpoint_925hPa { get; set; }
        public float?[]? Dewpoint_900hPa { get; set; }
        public float?[]? Dewpoint_850hPa { get; set; }
        public float?[]? Dewpoint_800hPa { get; set; }
        public float?[]? Dewpoint_700hPa { get; set; }
        public float?[]? Dewpoint_600hPa { get; set; }
        public float?[]? Dewpoint_500hPa { get; set; }
        public float?[]? Dewpoint_400hPa { get; set; }
        public float?[]? Dewpoint_300hPa { get; set; }
        public float?[]? Dewpoint_250hPa { get; set; }
        public float?[]? Dewpoint_200hPa { get; set; }
        public float?[]? Dewpoint_150hPa { get; set; }
        public float?[]? Dewpoint_100hPa { get; set; }
        public float?[]? Dewpoint_70hPa { get; set; }
        public float?[]? Dewpoint_50hPa { get; set; }
        public object?[]? Dewpoint_30hPa { get; set; }
        public int?[]? Relativehumidity_1000hPa { get; set; }
        public int?[]? Relativehumidity_975hPa { get; set; }
        public int?[]? Relativehumidity_950hPa { get; set; }
        public int?[]? Relativehumidity_925hPa { get; set; }
        public int?[]? Relativehumidity_900hPa { get; set; }
        public int?[]? Relativehumidity_875hPa { get; set; }
        public int?[]? Relativehumidity_850hPa { get; set; }
        public int?[]? Relativehumidity_825hPa { get; set; }
        public int?[]? Relativehumidity_800hPa { get; set; }
        public int?[]? Relativehumidity_775hPa { get; set; }
        public int?[]? Relativehumidity_750hPa { get; set; }
        public int?[]? Relativehumidity_725hPa { get; set; }
        public int?[]? Relativehumidity_700hPa { get; set; }
        public int?[]? Relativehumidity_675hPa { get; set; }
        public int?[]? Relativehumidity_650hPa { get; set; }
        public int?[]? Relativehumidity_625hPa { get; set; }
        public int?[]? Relativehumidity_600hPa { get; set; }
        public int?[]? Relativehumidity_575hPa { get; set; }
        public int?[]? Relativehumidity_550hPa { get; set; }
        public int?[]? Relativehumidity_525hPa { get; set; }
        public int?[]? Relativehumidity_500hPa { get; set; }
        public int?[]? Relativehumidity_400hPa { get; set; }
        public int?[]? Relativehumidity_300hPa { get; set; }
        public int?[]? Relativehumidity_250hPa { get; set; }
        public int?[]? Relativehumidity_200hPa { get; set; }
        public int?[]? Relativehumidity_150hPa { get; set; }
        public int?[]? Relativehumidity_100hPa { get; set; }
        public int?[]? Relativehumidity_70hPa { get; set; }
        public int?[]? Relativehumidity_50hPa { get; set; }
        public int?[]? Relativehumidity_30hPa { get; set; }
        public int?[]? Cloudcover_1000hPa { get; set; }
        public int?[]? Cloudcover_975hPa { get; set; }
        public int?[]? Cloudcover_950hPa { get; set; }
        public int?[]? Cloudcover_925hPa { get; set; }
        public int?[]? Cloudcover_900hPa { get; set; }
        public int?[]? Cloudcover_875hPa { get; set; }
        public int?[]? Cloudcover_850hPa { get; set; }
        public int?[]? Cloudcover_825hPa { get; set; }
        public int?[]? Cloudcover_800hPa { get; set; }
        public int?[]? Cloudcover_775hPa { get; set; }
        public int?[]? Cloudcover_750hPa { get; set; }
        public int?[]? Cloudcover_725hPa { get; set; }
        public int?[]? Cloudcover_700hPa { get; set; }
        public int?[]? Cloudcover_675hPa { get; set; }
        public int?[]? Cloudcover_650hPa { get; set; }
        public int?[]? Cloudcover_625hPa { get; set; }
        public int?[]? Cloudcover_600hPa { get; set; }
        public int?[]? Cloudcover_575hPa { get; set; }
        public int?[]? Cloudcover_550hPa { get; set; }
        public int?[]? Cloudcover_525hPa { get; set; }
        public int?[]? Cloudcover_500hPa { get; set; }
        public int?[]? Cloudcover_400hPa { get; set; }
        public int?[]? Cloudcover_300hPa { get; set; }
        public int?[]? Cloudcover_250hPa { get; set; }
        public int?[]? Cloudcover_200hPa { get; set; }
        public int?[]? Cloudcover_150hPa { get; set; }
        public int?[]? Cloudcover_100hPa { get; set; }
        public int?[]? Cloudcover_70hPa { get; set; }
        public int?[]? Cloudcover_50hPa { get; set; }
        public int?[]? Cloudcover_30hPa { get; set; }
        public float?[]? Windspeed_1000hPa { get; set; }
        public float?[]? Windspeed_975hPa { get; set; }
        public float?[]? Windspeed_950hPa { get; set; }
        public float?[]? Windspeed_925hPa { get; set; }
        public float?[]? Windspeed_900hPa { get; set; }
        public float?[]? Windspeed_850hPa { get; set; }
        public float?[]? Windspeed_800hPa { get; set; }
        public float?[]? Windspeed_700hPa { get; set; }
        public float?[]? Windspeed_600hPa { get; set; }
        public float?[]? Windspeed_500hPa { get; set; }
        public float?[]? Windspeed_400hPa { get; set; }
        public float?[]? Windspeed_300hPa { get; set; }
        public float?[]? Windspeed_250hPa { get; set; }
        public float?[]? Windspeed_200hPa { get; set; }
        public float?[]? Windspeed_150hPa { get; set; }
        public float?[]? Windspeed_100hPa { get; set; }
        public float?[]? Windspeed_70hPa { get; set; }
        public float?[]? Windspeed_50hPa { get; set; }
        public float?[]? Windspeed_30hPa { get; set; }
        public int?[]? Winddirection_1000hPa { get; set; }
        public int?[]? Winddirection_975hPa { get; set; }
        public int?[]? Winddirection_950hPa { get; set; }
        public int?[]? Winddirection_925hPa { get; set; }
        public int?[]? Winddirection_900hPa { get; set; }
        public int?[]? Winddirection_850hPa { get; set; }
        public int?[]? Winddirection_800hPa { get; set; }
        public int?[]? Winddirection_700hPa { get; set; }
        public int?[]? Winddirection_600hPa { get; set; }
        public int?[]? Winddirection_500hPa { get; set; }
        public int?[]? Winddirection_400hPa { get; set; }
        public int?[]? Winddirection_300hPa { get; set; }
        public int?[]? Winddirection_250hPa { get; set; }
        public int?[]? Winddirection_200hPa { get; set; }
        public int?[]? Winddirection_150hPa { get; set; }
        public int?[]? Winddirection_100hPa { get; set; }
        public int?[]? Winddirection_70hPa { get; set; }
        public int?[]? Winddirection_50hPa { get; set; }
        public int?[]? Winddirection_30hPa { get; set; }
        public float?[]? Geopotential_height_1000hPa { get; set; }
        public float?[]? Geopotential_height_975hPa { get; set; }
        public float?[]? Geopotential_height_950hPa { get; set; }
        public float?[]? Geopotential_height_925hPa { get; set; }
        public float?[]? Geopotential_height_900hPa { get; set; }
        public float?[]? Geopotential_height_875hPa { get; set; }
        public float?[]? Geopotential_height_850hPa { get; set; }
        public float?[]? Geopotential_height_825hPa { get; set; }
        public float?[]? Geopotential_height_800hPa { get; set; }
        public float?[]? Geopotential_height_775hPa { get; set; }
        public float?[]? Geopotential_height_750hPa { get; set; }
        public float?[]? Geopotential_height_725hPa { get; set; }
        public float?[]? Geopotential_height_700hPa { get; set; }
        public float?[]? Geopotential_height_675hPa { get; set; }
        public float?[]? Geopotential_height_650hPa { get; set; }
        public float?[]? Geopotential_height_625hPa { get; set; }
        public float?[]? Geopotential_height_600hPa { get; set; }
        public float?[]? Geopotential_height_575hPa { get; set; }
        public float?[]? Geopotential_height_550hPa { get; set; }
        public float?[]? Geopotential_height_525hPa { get; set; }
        public float?[]? Geopotential_height_500hPa { get; set; }
        public float?[]? Geopotential_height_400hPa { get; set; }
        public float?[]? Geopotential_height_300hPa { get; set; }
        public float?[]? Geopotential_height_250hPa { get; set; }
        public float?[]? Geopotential_height_200hPa { get; set; }
        public float?[]? Geopotential_height_150hPa { get; set; }
        public float?[]? Geopotential_height_100hPa { get; set; }
        public float?[]? Geopotential_height_70hPa { get; set; }
        public float?[]? Geopotential_height_50hPa { get; set; }
        public float?[]? Geopotential_height_30hPa { get; set; }
        public float?[]? Uv_index { get; set; }
        public float?[]? Uv_index_clear_sky { get; set; }
        public int?[]? Is_day { get; set; }
        public int?[]? Precipitation_probability { get; set; }
    }
}
