<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <PackageId>$(AssemblyName).dotnet.client.sdk</PackageId>
    <Title>OpenMeteo Dotnet Client SDK Library</Title>
    <Version>0.0.3</Version>
    <Authors>AlienDwarf, colinnuk</Authors>
    <Company />
    <Product>$(AssemblyName) Dotnet Client SDK Library</Product>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/colinnuk/open-meteo-dotnet-client-sdk</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>OpenMeteo, Weather, Forecast, Meteorology, Api, Geodata, Weathercode</PackageTags>
    <Copyright>Copyright © 2025 AlienDwarf, colinnuk</Copyright>
    <AssemblyVersion>0.0.1</AssemblyVersion>
    <FileVersion>0.0.1</FileVersion>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Description>A DotNet 8 Client SDK library for the Open-Meteo.com API.</Description>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Deterministic>True</Deterministic>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Deterministic>True</Deterministic>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GeoJSON.Text" Version="1.1.0" />
    <PackageReference Include="openmeteo_sdk" Version="1.26.0" />
    <PackageReference Include="ProjNET" Version="2.1.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.10" />
  </ItemGroup>

  </Project>
