name: Package, create new release and push to Nuget

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4
      with:
          versionSpec: '5.x'

    - name: Check out Code 
      uses: actions/checkout@v6
      with:
          fetch-depth: 0

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v4
      with:
          useConfigFile: true
          configFilePath: ./.github/gitversion.yml

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build dotnet 
      run: dotnet build --configuration release /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} /p:AssemblyVersion=${{ steps.gitversion.outputs.AssemblySemVer }} /p:InformationalVersion=${{ steps.gitversion.outputs.InformationalVersion }} --no-restore
      
    - name: Run tests
      run: dotnet test --filter "TestCategory!=Integration" --configuration Release /p:Version=${{ steps.gitversion.outputs.AssemblySemVer }} --no-build --verbosity normal
      
    - name: Create Release for Tag
      if: github.ref == 'refs/heads/master'
      uses: yyx990803/release-tag@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.gitversion.outputs.FullSemVer }}

    - name: Package nuget
      run: |
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          dotnet pack ./OpenMeteo/OpenMeteo.csproj --configuration release -o:package /p:PackageVersion=${{ steps.gitversion.outputs.FullSemVer }}
        else
          dotnet pack ./OpenMeteo/OpenMeteo.csproj --configuration release -o:package /p:PackageVersion=${{ steps.gitversion.outputs.AssemblySemVer }}
        fi

    - name: Push generated package to NuGet.org
      run: dotnet nuget push ./package/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate